ingress:
  enabled: true
  host: longhorn.local
persistence:
  defaultClassReplicaCount: 1
  defaultClass: false
csi:
  attacherReplicaCount: 1
  provisionerReplicaCount: 1
  resizerReplicaCount: 1
  snapshotterReplicaCount: 1
defaultSettings:
  defaultReplicaCount: 1
