apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: kasten-zfs
parameters:
  recordsize: "4k"
  compression: "off"
  dedup: "off"
  fstype: "zfs"
  poolname: "kasten-pool"
provisioner: zfs.csi.openebs.io
